
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from "@prisma/config";
import * as dotenv from "dotenv";
import dotenvExpand from "dotenv-expand"; 
const myEnv = dotenv.config();
dotenvExpand.expand(myEnv);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
